### PR TITLE
Fix the app crashing on Nougat when app detail screen is opened

### LINKED ISSUE #1199: [BUG] Crash when scrolling to the bottom of an app's details page
**Describe the bug**
Since the upgrade to 0.6.8, scrolling to the bottom of an app's page (where the available versions list should appear) causes a crash.

**To Reproduce**
1. Open the details page of an app.
2. Scroll to the bottom.

**Stack trace**
```
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 29611
java.lang.NoSuchMethodError: No virtual method setTooltipText(Ljava/lang/CharSequence;)V in class Landroid/widget/ImageView; or its super classes (declaration of 'android.widget.ImageView' appears in /system/framework/framework.jar:classes2.dex)
    at com.looker.droidify.ui.appDetail.AppDetailAdapter.onBindViewHolder(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:341)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:1450)
    at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:64)
    at androidx.recyclerview.widget.GapWorker.prefetch(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:177)
    at androidx.recyclerview.widget.GapWorker.run(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:70)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6816)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Smartphone (please complete the following information):**
Samsung Android 7.1.

Does **not** happen on Samsung Android 11.

### PR DESCRIPTION
**Pull request by xinkev**
This issue occurs because `setTooltipText` is only available starting from API level 26.
The fix replaces it with `TooltipCompat.setTooltipText`.

Fixes #1199

### CODE REVIEW

**Comment by Iamlooker** [comment]
Thanks 🙌

**Comment by Iamlooker** [comment]
@Careless is this a android nougat thing? Or is it also happening on later versions too?

**Comment by xinkev** [comment]
@Iamlooker Probably just Nougat. However, this is a different issue. I initially thought this would be related to `ImageView` since they mentioned screenshots, but this is caused by `android.R.attr.colorError` which is only added in API level 26. Here's the log:
```
23:18:15.194  E  FATAL EXCEPTION: main
                 Process: com.looker.droidify.debug, PID: 4306
                 android.content.res.Resources$NotFoundException: Resource ID #0x0
                 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
                 	at android.content.res.Resources.getValue(Resources.java:1290)
                 	at androidx.core.content.res.ResourcesCompat.isColorInt(ResourcesCompat.java:305)
                 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:253)
                 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:234)
                 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:516)
                 	at com.looker.droidify.utility.common.extension.ContextKt.getColorFromAttr(Context.kt:98)
                 	at com.looker.droidify.ui.appDetail.AppDetailAdapter$InstallButtonViewHolder.<init>(AppDetailAdapter.kt:451)
                 	at com.looker.droidify.ui.appDetail.AppDetailAdapter.onCreateViewHolder(AppDetailAdapter.kt:1152)
                 	at com.looker.droidify.ui.appDetail.AppDetailAdapter.onCreateViewHolder(AppDetailAdapter.kt:94)
                 	at com.looker.droidify.widget.EnumRecyclerAdapter.onCreateViewHolder(EnumRecyclerAdapter.kt:24)
                 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7889)
                 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6969)
                 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6853)
                 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6849)
                 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2422)
                 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1722)
                 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1682)
                 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:747)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4737)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4459)
                 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5011)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
                 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
                 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:145)
                 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
                 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2461)
                 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
                 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
                 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
                 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
                 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
23:18:15.194  E  	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
                 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                 	at android.view.View.layout(View.java:17637)
                 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
                 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                 	at android.view.Choreographer.doFrame(Choreographer.java:621)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                 	at android.os.Handler.handleCallback(Handler.java:751)
                 	at android.os.Handler.dispatchMessage(Handler.java:95)
                 	at android.os.Looper.loop(Looper.java:154)
                 	at android.app.ActivityThread.main(ActivityThread.java:6119)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
