### ISSUE TITLE
[BUG] Crash when scrolling to the bottom of an app's details page

### ISSUE THREAD

**Issue by opk12** [Droid-ify/client#1199]
**Describe the bug**
Since the upgrade to 0.6.8, scrolling to the bottom of an app's page (where the available versions list should appear) causes a crash.

**To Reproduce**
1. Open the details page of an app.
2. Scroll to the bottom.

**Stack trace**
```
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 29611
java.lang.NoSuchMethodError: No virtual method setTooltipText(Ljava/lang/CharSequence;)V in class Landroid/widget/ImageView; or its super classes (declaration of 'android.widget.ImageView' appears in /system/framework/framework.jar:classes2.dex)
    at com.looker.droidify.ui.appDetail.AppDetailAdapter.onBindViewHolder(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:341)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:1450)
    at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:64)
    at androidx.recyclerview.widget.GapWorker.prefetch(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:177)
    at androidx.recyclerview.widget.GapWorker.run(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:70)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6816)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Smartphone (please complete the following information):**
Samsung Android 7.1.

Does **not** happen on Samsung Android 11.

**Comment by Careless** [comment]
sorry for not checking for duplicate errors.
thank you for fixing.

**Comment by Iamlooker** [comment]
This will be released by end of this week

**Comment by Careless** [comment]
No worries. For now, I am using 0.6.6 without issue.
Whenever you feel it is ready, I will install the update and test it.

**Comment by Iamlooker** [comment]
Reopening because of [this report](https://github.com/Droid-ify/client/pull/1203#issuecomment-3951922624)

**Comment by xinkev** [comment]
@Iamlooker 
I make a PR.  #1241
What do you think?

**Comment by Careless** [comment]
this is still crashing in landscape mode on android 7.1.2 using droid-ify 0.7.1.

as soon as I scroll down passed the green 'install' or 'launch' action button, it crashes and force closes the app and returns to launcher.

i can't seem to get logfox to see it as a crash so that i can show the actual output, but exporting items with a 'droidify' filter shows these results:

```
1774659760.486  1000   516  4431 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.looker.droidify/.MainActivity bnds=[60,812][453,887]} from uid 10085 on display 0
1774659760.603  1000   516  1328 I ActivityManager: Start proc 13330:com.looker.droidify/u0a99 for activity com.looker.droidify/.MainActivity
1774659762.902 10099 13330 13330 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.animation.ValueAnimator$DurationScaleChangeListener" on path: DexPathList[[zip file "/data/app/com.looker.droidify-1/base.apk"],nativeLibraryDirectories=[/data/app/com.looker.droidify-1/lib/arm, /data/app/com.looker.droidify-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
1774659762.905 10099 13330 13330 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.animation.ValueAnimator$DurationScaleChangeListener" on path: DexPathList[[zip file "/data/app/com.looker.droidify-1/base.apk"],nativeLibraryDirectories=[/data/app/com.looker.droidify-1/lib/arm, /data/app/com.looker.droidify-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
1774659762.907 10099 13330 13330 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.animation.ValueAnimator$DurationScaleChangeListener" on path: DexPathList[[zip file "/data/app/com.looker.droidify-1/base.apk"],nativeLibraryDirectories=[/data/app/com.looker.droidify-1/lib/arm, /data/app/com.looker.droidify-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
1774659763.468  1000   516   537 I ActivityManager: Displayed com.looker.droidify/.MainActivity: +2s901ms
1774659777.083  1000   516   537 W WindowManager: Force clearing orientation change: Window{4153460 u0 com.looker.droidify/com.looker.droidify.MainActivity}
1774659778.328  1000   516   537 W WindowManager: Force clearing freeze: AppWindowToken{2cdad token=Token{143a1d7 ActivityRecord{815dd56 u0 com.looker.droidify/.MainActivity t67}}}
1774659778.328  1000   516   537 I WindowManager: Screen frozen for +3s245ms due to AppWindowToken{2cdad token=Token{143a1d7 ActivityRecord{815dd56 u0 com.looker.droidify/.MainActivity t67}}}
1774659784.654  1000   516  3447 I WindowManager: WIN DEATH: Window{9c71ca7 u0 com.looker.droidify/com.looker.droidify.MainActivity}
1774659784.656  1000   516  3935 I ActivityManager: Process com.looker.droidify (pid 13330) has died
1774659784.661  1000   516  3935 W ActivityManager: Force removing ActivityRecord{815dd56 u0 com.looker.droidify/.MainActivity t67}: app died, no saved state
1774659790.123  1000   516 13429 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{23d92e1 0:com.looker.droidify/u0a99}
```

**Comment by opk12** [comment]
For Careless's crash, here's the log from LogFox, on Samsung Android 7.1 + Droid-ify 0.7.1. Always happens in landscape mode, I think it once happened in portrait mode.

```
28.03 10:46:55.483 DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
28.03 10:46:55.483 DEBUG: Build fingerprint: ...
28.03 10:46:55.483 DEBUG: Revision: '4'
28.03 10:46:55.483 DEBUG: ABI: 'arm'
28.03 10:46:55.483 DEBUG: pid: 10739, tid: 10775, name: RenderThread  >>> com.looker.droidify <<<
28.03 10:46:55.483 DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
28.03 10:46:55.491 DEBUG: Abort message: 'GL errors! frameworks/base/libs/hwui/BakedOpRenderer.cpp:75'
28.03 10:46:55.491 DEBUG:     r0 00000000  r1 00002a17  r2 00000006  r3 00000008
28.03 10:46:55.491 DEBUG:     r4 888ff978  r5 00000006  r6 888ff920  r7 0000010c
28.03 10:46:55.491 DEBUG:     r8 00000000  r9 a8b7126c  sl a8b712e4  fp a734d5c0
28.03 10:46:55.492 DEBUG:     ip 0000000b  sp 888feec0  lr a78740c7  pc a7876948  cpsr 200d0010
28.03 10:46:55.515 DEBUG: backtrace:
28.03 10:46:55.517 DEBUG:     #00 pc 0004a948  /system/lib/libc.so (tgkill+12)
28.03 10:46:55.517 DEBUG:     #01 pc 000480c3  /system/lib/libc.so (pthread_kill+34)
28.03 10:46:55.517 DEBUG:     #02 pc 0001dc4d  /system/lib/libc.so (raise+10)
28.03 10:46:55.517 DEBUG:     #03 pc 00019341  /system/lib/libc.so (__libc_android_abort+34)
28.03 10:46:55.517 DEBUG:     #04 pc 000173a8  /system/lib/libc.so (abort+4)
28.03 10:46:55.517 DEBUG:     #05 pc 0000c615  /system/lib/libcutils.so (__android_log_assert+112)
28.03 10:46:55.517 DEBUG:     #06 pc 00065cf5  /system/lib/libhwui.so
28.03 10:46:55.517 DEBUG:     #07 pc 00025a4f  /system/lib/libhwui.so
28.03 10:46:55.517 DEBUG:     #08 pc 00025689  /system/lib/libhwui.so
28.03 10:46:55.517 DEBUG:     #09 pc 00027277  /system/lib/libhwui.so
28.03 10:46:55.517 DEBUG:     #10 pc 0002a955  /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+80)
28.03 10:46:55.517 DEBUG:     #11 pc 0000e41d  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+140)
28.03 10:46:55.517 DEBUG:     #12 pc 0006a29d  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+80)
28.03 10:46:55.517 DEBUG:     #13 pc 00047b93  /system/lib/libc.so (_ZL15__pthread_startPv+22)
28.03 10:46:55.517 DEBUG:     #14 pc 00019fb1  /system/lib/libc.so (__start_thread+6)
```

**Comment by Careless** [comment]
> For Careless's crash, here's the log from LogFox, on Samsung Android 7.1 + Droid-ify 0.7.1. Always happens in landscape mode, I think it once happened in portrait mode.

thank you @opk12.
how did u retrieve the log? I would like to help more by contributing the same info if I can get it from the phone for this and future bugs.

**Comment by opk12** [comment]
@Careless If you do have the string `GL errors!` in the logcat, check if you have all checkboxes enabled in `Settings` - `Crashes` and consider filing it in the [LogFox issue tracker](https://github.com/F0x1d/LogFox/issues) as there is not apparently something similar reported.

Please also consider checking #1301 (same symptom but different stack trace) and looking for the string `Resources$NotFoundException` in that case.

Weirdly, I'm not getting those `ClassNotFoundException: Didn't find class "android.animation.ValueAnimator$DurationScaleChangeListener"` from your log in my logcat.

**Comment by Careless** [comment]
> [@Careless](https://github.com/Careless) If you do have the string `GL errors!` in the logcat, check if you have all checkboxes enabled in `Settings` - `Crashes` and consider filing it in the [LogFox issue tracker](https://github.com/F0x1d/LogFox/issues) as there is not apparently something similar reported.

I'm not sure what issue would i be filing with logfox. I don't think there is a problem with it specifically, it usually catches the crash. but for this error it's not. But i will check the settings you referred to.

> Please also consider checking https://github.com/Droid-ify/client/issues/1301 (same symptom but different stack trace) and looking for the string Resources$NotFoundException in that case.

that issue leads back to this page, which is also similar to this one I filed earlier, which leads back here as well. there's nothing else I can do except share logs, realistically.

https://github.com/Droid-ify/client/issues/1207

**Comment by opk12** [comment]
@Careless Precisely that LogFox did not find a crash log in the logcat (which is where all crashes go). There is 1 symptom (scroll down -> crash) but 3 error messages (`No virtual method setTooltipText` from 1199 and the dupe 1207, `GL errors!` from 1199, `Resources$NotFoundException` from 1301) so up to 3 underlying issues (an Android dev can tell how many exactly).

**Comment by Careless** [comment]
ok i will try to catch some more log data before submitting logfox bug.

any idea what is causing the droid-ify crash with the submitted information, anyway?

**Comment by opk12** [comment]
@Careless Sadly I have background knowledge in desktop Java but not Android. Let's give the dev some time and wait for a few days (also this is coinciding with the Easter holidays).

**Comment by DJCrashdummy** [comment]
> this is still crashing in landscape mode on android 7.1.2 using droid-ify 0.7.1.

> Always happens in landscape mode, I think it once happened in portrait mode.

i have to confirm and can reliable reproduce that Droid-ify crashes always in landscape mode and just on certain apps (like [_Conversations_](https://f-droid.org/en/packages/eu.siacs.conversations/), [_Simple Crypto Widget_](https://f-droid.org/en/packages/com.brentpanther.bitcoinwidget/) or [_bVNC Free_ from Izzys repo](https://apt.izzysoft.de/fdroid/index/apk/com.iiordanov.freebVNC)) in portrait mode. but yes, it also seems that Droid-ify 0.7.1 partly fixed it, because in Droid-ify 0.7.0 it always crashed even in portrait mode.
...if some (additional) logs are needed just ping me.

**Comment by Careless** [comment]
crashed again today while in portrait mode on 0.7.1

```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.looker.droidify, PID: 8841
AndroidRuntime: android.content.res.Resources$NotFoundException: Resource ID #0x0
AndroidRuntime: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
AndroidRuntime: 	at android.content.res.Resources.getValue(Resources.java:1290)
AndroidRuntime: 	at androidx.tracing.Trace.getColorStateList(r8-map-id-d1f8f46bd967d6929ac95186c3358f9924bf97fbb76cac7a8fd8717cdf509193:104)
AndroidRuntime: 	at com.google.android.material.behavior.HideLeftViewOnScrollDelegate.getColorFromAttr(r8-map-id-d1f8f46bd967d6929ac95186c3358f9924bf97fbb76cac7a8fd8717cdf509193:23)
AndroidRuntime: 	at com.looker.droidify.ui.appDetail.AppDetailAdapter.onBindViewHolder(r8-map-id-d1f8f46bd967d6929ac95186c3358f9924bf97fbb76cac7a8fd8717cdf509193:1805)
AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(r8-map-id-d1f8f46bd967d6929ac95186c3358f9924bf97fbb76cac7a8fd8717cdf509193:1434)
AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(r8-map-id-d1f8f46bd967d6929ac95186c3358f9924bf97fbb76cac7a8fd8717cdf509193:64)
AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetch(r8-map-id-d1f8f46bd967d6929ac95186c3358f9924bf97fbb76cac7a8fd8717cdf509193:176)
AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.run(r8-map-id-d1f8f46bd967d6929ac95186c3358f9924bf97fbb76cac7a8fd8717cdf509193:70)
AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

is this fixed in 0.7.2 with the https://github.com/Droid-ify/client/pull/1241 commits?
