### PR TITLE
Fix app detail screen crashing on Nougat

### LINKED ISSUE #1199: [BUG] Crash when scrolling to the bottom of an app's details page
**Describe the bug**
Since the upgrade to 0.6.8, scrolling to the bottom of an app's page (where the available versions list should appear) causes a crash.

**To Reproduce**
1. Open the details page of an app.
2. Scroll to the bottom.

**Stack trace**
```
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 29611
java.lang.NoSuchMethodError: No virtual method setTooltipText(Ljava/lang/CharSequence;)V in class Landroid/widget/ImageView; or its super classes (declaration of 'android.widget.ImageView' appears in /system/framework/framework.jar:classes2.dex)
    at com.looker.droidify.ui.appDetail.AppDetailAdapter.onBindViewHolder(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:341)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:1450)
    at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:64)
    at androidx.recyclerview.widget.GapWorker.prefetch(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:177)
    at androidx.recyclerview.widget.GapWorker.run(r8-map-id-5004630702d2bba8e754764090f40d29fa371eab32e7760d9faa95e05a9c16bb:70)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6816)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Smartphone (please complete the following information):**
Samsung Android 7.1.

Does **not** happen on Samsung Android 11.

### PR DESCRIPTION
**Pull request by xinkev**
Fixes  #1199  
This prevents a crash on Nougat which happens because `AppDetailAdapter.kt` is referencing `android.R.attr.colorError`, which was introduced in API 26.
A custom theme attribute (`errorColor`) was added to provide a fallback on pre-26 devices.

Verified on Nougat and Android 16.

### CODE REVIEW

File: app/src/main/res/values/colors.xml [hunk 1]
```diff
@@ -1,6 +1,7 @@
 <?xml version="1.0" encoding="utf-8"?>
 <resources>
     <color name="pitch_black">#000000</color>
+    <color name="colorError"></color>
```
Comment (Iamlooker) [inline app/src/main/res/values/colors.xml]: Is this needed if its empty?

**Review by Iamlooker — CHANGES_REQUESTED** [review]

File: app/src/main/res/values/colors.xml (hunk 1 above)
Comment (Iamlooker) [reply app/src/main/res/values/colors.xml]: Use the following 2 error colors instead:
`md_theme_l_error`, `md_theme_d_error`

For light and dark theme respectively

**Comment by Iamlooker** [comment]
Awesome work 😉
